<?php

namespace Recite\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findOne($idOrTitle){
        if(is_numeric($idOrTitle)){
            return $this->find((int)$idOrTitle);
        }

        return $this->findOneByTitle($idOrTitle);
    }
}
