<?php

namespace Recite\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZiExampleRepository extends EntityRepository
{
}
