jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        Recite\DataBundle\Entity\User:
            algorithm:   sha512
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        file:
            memory:
                users:
                    user: {password: whosyourdaddy, roles: [ROLE_USER]}

        db:
            entity:
                class: Recite\DataBundle\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: recite_authentication_listener
                failure_handler: recite_authentication_listener
                
            logout:
                path:  /logout
                target: /
                success_handler: recite_authentication_listener

            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
