jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        Recite\DataBundle\Entity\User:
            algorithm:   sha512
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        file:
            memory:
                users:
                    user: {password: whosyourdaddy, roles: [ROLE_USER]}

        db:
            entity: {class: Recite\DataBundle\Entity\User, property: email}

        all:
            chain:
                providers: [file, db]

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: recite_authentication_listener
                failure_handler: recite_authentication_listener
                username_parameter: email
                password_parameter: password

            provider: all

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
                remember_me_parameter: remember_me
                
            logout:
                path:  /logout
                target: /
                success_handler: recite_authentication_listener

            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
