<?php

namespace Recite\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserProviderInterface
{
    public function loadUserByUsername($email) {
        $user = $this->findOneByEmail($email);

        if(is_null($user)){
            $e = new UsernameNotFoundException();
            $e->setUsername($email);

            throw $e;
        }

        return $user;
    }

    public function refreshUser(UserInterface $user) {
        return $this->find($user->getId());
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class
            || is_subclass_of($class, $this->getEntityName());
    }

    public function isEmailExists($email){
        return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('count(u.id)')
                ->from('ReciteDataBundle:User', 'u')
                ->where('u.email=:e')
                ->getQuery()
                ->setMaxResults(1)
                ->setParameter('e', $email)
                ->getSingleScalarResult();
    }
}
